### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by itsmedhaaz** [immdipu/CINEMAA#1]
The Episode list does not appear when clicking the Season Button.. Please fix that immediately

**Comment by immdipu** [comment]
it's working fine on my device. Check again

**Comment by itsmedhaaz** [comment]
![IMG_20220717_092428](https://user-images.githubusercontent.com/75169859/179381306-ced16ce4-9d1f-422e-8214-1782da7706b9.jpg)
In the Season Section, not showing anything, I deploy in Vercel... Please fix well
